import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { register } from '@tokens-studio/sd-transforms';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const designSystemRoot = path.resolve(__dirname, '../..');
const genshiRoot = path.join(designSystemRoot, 'tokens/source/genshi');
const overridesRoot = path.join(designSystemRoot, 'tokens/source/overrides');
const generatedRoot = path.join(designSystemRoot, 'tokens/generated');
const mappingsRoot = path.join(designSystemRoot, 'mappings');
const packageDistDir = path.resolve(__dirname, 'dist');

function deepMerge(target, source) {
  for (const [key, value] of Object.entries(source)) {
    if (
      value &&
      typeof value === 'object' &&
      !Array.isArray(value) &&
      !(value.$value !== undefined && value.$type !== undefined)
    ) {
      target[key] = deepMerge(target[key] ?? {}, value);
    } else {
      target[key] = value;
    }
  }
  return target;
}

function loadTokenSets(rootDir) {
  const metadataPath = path.join(rootDir, '$metadata.json');
  if (!fs.existsSync(metadataPath)) {
    return {};
  }

  const metadata = JSON.parse(fs.readFileSync(metadataPath, 'utf8'));
  let merged = {};

  for (const setPath of metadata.tokenSetOrder ?? []) {
    const filePath = path.join(rootDir, `${setPath}.json`);
    if (!fs.existsSync(filePath)) {
      console.warn(`Skipping missing token set: ${setPath}`);
      continue;
    }
    merged = deepMerge(merged, JSON.parse(fs.readFileSync(filePath, 'utf8')));
  }

  return merged;
}

function mergeTokenSets() {
  const genshi = loadTokenSets(genshiRoot);
  const overrides = loadTokenSets(overridesRoot);
  const merged = deepMerge(genshi, overrides);
  const mergedPath = path.join(designSystemRoot, 'tokens/_merged.json');
  fs.writeFileSync(mergedPath, JSON.stringify(merged, null, 2));
  return mergedPath;
}

function loadAliases() {
  const aliasesPath = path.join(mappingsRoot, 'aliases.json');
  const raw = JSON.parse(fs.readFileSync(aliasesPath, 'utf8'));
  return Object.fromEntries(
    Object.entries(raw).filter(([key]) => key.startsWith('--'))
  );
}

/** Convenience aliases: canonical --gsh-* → shorter public --gsh-* (canonical is source of truth). */
function buildConvenienceAliasCss(aliases) {
  const lines = Object.entries(aliases).map(
    ([canonicalVar, convenienceVar]) =>
      `  ${convenienceVar}: var(${canonicalVar});`
  );
  return `/**\n * Genshi convenience token aliases — derived from canonical CSS variables.\n * Do not edit; generated by packages/tokens/build.mjs\n */\n:root {\n${lines.join('\n')}\n}\n`;
}

function buildTokensTs(aliases) {
  const entries = Object.entries(aliases)
    .map(([, convenienceVar]) => {
      const key = convenienceVar
        .replace(/^--/, '')
        .replace(/-/g, '_')
        .toUpperCase();
      return `  ${key}: 'var(${convenienceVar})',`;
    })
    .join('\n');

  return `/**\n * Generated Genshi token CSS variable references.\n * Do not edit; generated by packages/tokens/build.mjs\n */\nexport const gshVars = {\n${entries}\n} as const;\n\nexport type GshVarKey = keyof typeof gshVars;\n`;
}

function buildTailwindPreset(aliases) {
  const theme = {};
  for (const [, convenienceVar] of Object.entries(aliases)) {
    const parts = convenienceVar.replace(/^--gsh-/, '').split('-');
    let cursor = theme;
    for (let i = 0; i < parts.length - 1; i += 1) {
      cursor[parts[i]] = cursor[parts[i]] ?? {};
      cursor = cursor[parts[i]];
    }
    cursor[parts[parts.length - 1]] = `var(${convenienceVar})`;
  }

  return `/**\n * Tailwind preset backed by Genshi CSS variables.\n * Do not edit; generated by packages/tokens/build.mjs\n */\n/** @type {import('tailwindcss').Config} */\nexport default {\n  theme: {\n    extend: ${JSON.stringify(theme, null, 4).replace(/"var\(([^)]+)\)"/g, 'var($1)')},\n  },\n};\n`;
}

register(StyleDictionary);

fs.mkdirSync(path.join(generatedRoot, 'css'), { recursive: true });
fs.mkdirSync(path.join(generatedRoot, 'ts'), { recursive: true });
fs.mkdirSync(path.join(generatedRoot, 'tailwind'), { recursive: true });
fs.mkdirSync(packageDistDir, { recursive: true });

const mergedPath = mergeTokenSets();
const aliases = loadAliases();

const sd = new StyleDictionary({
  source: [mergedPath],
  preprocessors: ['tokens-studio'],
  platforms: {
    css: {
      transformGroup: 'tokens-studio',
      transforms: ['name/kebab'],
      buildPath: `${generatedRoot}/css/`,
      files: [
        {
          destination: 'tokens.css',
          format: 'css/variables',
          options: { outputReferences: true },
        },
      ],
    },
  },
});

await sd.buildAllPlatforms();

const baseCss = fs.readFileSync(
  path.join(generatedRoot, 'css/tokens.css'),
  'utf8'
);
const aliasCss = buildConvenienceAliasCss(aliases);
const combinedCss = `${baseCss}\n\n${aliasCss}`;

fs.writeFileSync(path.join(generatedRoot, 'css/tokens.css'), combinedCss);
fs.writeFileSync(path.join(generatedRoot, 'css/aliases.css'), aliasCss);
fs.writeFileSync(
  path.join(generatedRoot, 'ts/tokens.ts'),
  buildTokensTs(aliases)
);
fs.writeFileSync(
  path.join(generatedRoot, 'tailwind/preset.js'),
  buildTailwindPreset(aliases)
);

fs.writeFileSync(path.join(packageDistDir, 'tokens.css'), combinedCss);
fs.copyFileSync(
  path.join(generatedRoot, 'ts/tokens.ts'),
  path.join(packageDistDir, 'tokens.ts')
);
fs.copyFileSync(
  path.join(generatedRoot, 'tailwind/preset.js'),
  path.join(packageDistDir, 'tailwind-preset.js')
);

console.log('Built', path.join(generatedRoot, 'css/tokens.css'));
console.log('Built', path.join(generatedRoot, 'ts/tokens.ts'));
console.log('Built', path.join(generatedRoot, 'tailwind/preset.js'));
